Elasticsearch
lbryio/lbry-sdk pull request #3153
Opened 2021-01-20 04:59 UTC by shyba

2021-03-15 20:05 UTC, eukreign requested changes
- `torba` was merged into `lbry-sdk` and i believe the name was deprecated, you should use either `wallet`, `wallet-server` or `hub`
- `tests/unit/wallet/server/test_sqldb.py` was deleted but what replaces all of those tests?

2021-03-22 18:05 UTC, jackrobison commented on docker/docker-compose-wallet-server.yml
> +    image: lbry/wallet-server:${WALLET_SERVER_TAG:-development}
should be `latest-release`, once this is merged and released it'll work, we can manually change to `development` for testing

2021-03-22 18:16 UTC, jackrobison commented on lbry/wallet/rpc/util.py
> +from functools import lru_cache
should `lbry.utils.LRUCache` be used here instead? `functools.lru_cache` has a `RLock`

2021-03-22 20:00 UTC, jackrobison requested changes

2021-03-24 20:44 UTC, merged