adding access control headers
lbryio/lbry-sdk pull request #3247
Opened 2021-03-28 03:57 UTC by freakypie

2021-03-30 13:42 UTC, eukreign commented
@freakypie thanks for the PR. can you add a unit test which verifies that this change actually fixes the problem or at least that the OPTIONs stuff is working. we already have some existing tests related to this and you can add yours there: https://github.com/lbryio/lbry-sdk/blob/master/tests/unit/lbrynet_daemon/test_allowed_origin.py

2021-03-30 13:42 UTC, eukreign requested changes
@freakypie thanks for the PR. can you add a unit test which verifies that this change actually fixes the problem or at least that the OPTIONs stuff is working. we already have some existing tests related to this and you can add yours there: https://github.com/lbryio/lbry-sdk/blob/master/tests/unit/lbrynet_daemon/test_allowed_origin.py

2021-03-30 21:51 UTC, freakypie commented
I did look at the tests you suggested @eukreign , however, I think that they aren't related enough for me to be able to easily copy and paste one (as they seem to test before a request is made). I tried to find another test that showed getting a response from the lbrynet server, but I'm not familiar enough with this so it's going to take me a while.

2021-04-06 19:20 UTC, eukreign approved these changes

2021-04-06 21:12 UTC, merged