file_manager: trap the exception if the claim is not a stream
lbryio/lbry-sdk pull request #3364
Opened 2021-07-14 23:10 UTC by belikor

If `claim` is not a stream, the line `claim.stream.source.bt_infohash` will raise a `ValueError` exception because `claim.stream` does not contain a valid object.

This will happen if we try to download a claim that is in fact a `collection` (a playlist).
```
lbrynet get lbry://@something#e/My-New-List#f
```

Since at the moment we don't trap this exception, it prints the entire trace of the exception.
```
Traceback (most recent call last):
  File "/opt/git/lbry-sdk/lbry/file/file_manager.py", line 117, in download_from_uri
    if claim.stream.source.bt_infohash:
  File "/opt/git/lbry-sdk/lbry/schema/claim.py", line 55, in stream
    return Stream(self)
  File "/opt/git/lbry-sdk/lbry/schema/claim.py", line 108, in __init__
    self.message = self.claim.get_message(self.claim_type)
  File "/opt/git/lbry-sdk/lbry/schema/claim.py", line 46, in get_message
    raise ValueError(f'Claim is not a {type_name}.')
```

Therefore we trap this `ValueError` to avoid showing the entire trace.
We don't do anything with the exception, we just raise it again so that it is handled by the calling code `daemon.jsonrpc_get`.

Then it will show an appropriate message.
```
WARNING  lbry.extras.daemon.daemon:1106: Error downloading lbry://@something#e/My-New-List#f: Claim is not a stream.
```

2021-07-19 16:44 UTC, eukreign requested changes
`ValueError` is too generic of an exception to catch here, this will make it hard to find actual bugs later.

I think we we should just avoid accessing `claim.stream.source.bt_infohash` on a claim that is not a stream. I'd suggest fixing the code in `File "/opt/git/lbry-sdk/lbry/file/file_manager.py", line 117, in download_from_uri` to guard the access by first checking that the claim actually has a stream.

2021-07-19 22:58 UTC, belikor commented
>  I'd suggest fixing the code in `File "/opt/git/lbry-sdk/lbry/file/file_manager.py", line 117, in download_from_uri` to guard the access by first checking that the claim actually has a stream.

Okay, I thought so too, but that's a more involved solution, and at the moment I don't know the code that well, so that's what I decided to just trap `ValueError`. As it produces a simple explanation (`Claim is not a stream.`) I thought that was enough.

2021-08-09 21:09 UTC, lyoshenka commented
@belikor what's next here? does it need another review?

2021-08-09 21:54 UTC, belikor commented
> @belikor what's next here? does it need another review?

No. I haven't touched this at all. Lex mentioned a few steps to try but I haven't tested that.

2021-08-15 22:34 UTC, belikor commented
Okay, I updated the pull request. Now we raise `ResolveError` if `claim.is_collection` or if `not claim.is_stream` before accessing `claim.stream.source.bt_infohash`.

We trap it later in the code so we don't have the entire traceback printed to the terminal.

This also helps in case we try to download a channel, which raises the same error.
```
lbrynet get '@something#e'
```

```
WARNING  lbry.file.file_manager:254: Failed to download @something#e: Failed to resolve 'cannot download a channel claim, specify a /path'.
WARNING  lbry.extras.daemon.daemon:1106: Error downloading @something#e: Failed to resolve 'cannot download a channel claim, specify a /path'.
```

2021-09-01 14:15 UTC, eukreign requested changes
I don't think it's fair to say that the resolve failed. If you get a claim for a URL then by definition the resolve succeeded. The issue is that what got resolved turns out not to be a file. I think a more specific exception would be better, you may re-use the same exception as I suggest in your other PR here: https://github.com/lbryio/lbry-sdk/pull/3403#pullrequestreview-743982040

2021-09-04 00:41 UTC, belikor commented
Now we don't use `ResolveError`, we use `InvalidStreamURLError`. This pull request now follows from #3403.

It traps those claims that are not streams such as reposts and collections, as well as channels.
```
lbrynet get collection-music
lbrynet get LUKAS-LION---1984:a
lbrynet get @lbry
``` 

```
WARNING  lbry.file.file_manager:258: Failed to download collection-music: Invalid LBRY stream URL: 'collection-music'
WARNING  lbry.extras.daemon.daemon:1114: Error downloading collection-music: Claim is not a stream.
WARNING  lbry.file.file_manager:258: Failed to download LUKAS-LION---1984:a: Invalid LBRY stream URL: 'LUKAS-LION---1984:a'
WARNING  lbry.extras.daemon.daemon:1114: Error downloading LUKAS-LION---1984:a: Claim is not a stream.
WARNING  lbry.file.file_manager:258: Failed to download @lbry: Invalid LBRY stream URL: '@lbry'
WARNING  lbry.extras.daemon.daemon:1114: Error downloading @lbry: Invalid LBRY stream URL: '@lbry'
```

2021-09-09 21:14 UTC, lyoshenka commented
@belikor looks like you made some changes? do you want another review? if so, click the "Re-request review" button next to @eukreign 's name on the right side. this will also automatically assign him.

in general, our process is that whoever the issue is assigned to, they are responsible for taking the next step.

2021-09-13 01:30 UTC, belikor commented
Okay, now it's rebased.

2021-09-13 02:31 UTC, eukreign commented
this PR conflicts with your other PR, let's get that one merged first, then you can rebase this one

2021-10-04 15:34 UTC, kauffj commented
Using #3403

2021-10-04 15:34 UTC, closed without merging