file_manager: handle the response better when a claim is not found
lbryio/lbry-sdk pull request #3397
Opened 2021-08-16 22:09 UTC by belikor

This is similar to #3364 and #3396.

When using `lbrynet get URL`, if the URL does not exist it will raise a `ResolveError` exception which will produce a whole backtrace.

For example
```
lbrynet get Non-existing
```

```
Traceback (most recent call last):
  File "/opt/git/lbry-sdk/lbry/file/file_manager.py", line 107, in download_from_uri
    raise ResolveError(f"Failed to resolve stream at '{uri}': {txo}")
lbry.error.ResolveError: Failed to resolve 'Failed to resolve stream at 'Non-existing': {'error': {'name': 'NOT_FOUND', 'text': 'Could not find claim at "Non-existing".'}}'.
WARNING  lbry.extras.daemon.daemon:1106: Error downloading Non-existing: Failed to resolve 'Failed to resolve stream at 'Non-existing': {'error': {'name': 'NOT_FOUND', 'text': 'Could not find claim at "Non-existing".'}}'.
```

Not only that, the error message has a nested message inside so the full output is quite ugly.

-------------------------------------------------------------------

Now we will find if the `'error'` key is in the response. If it is, and the `'text'` key is also present, we will raise `ResolveError` with the message stored in this text.

We will trap `ResolveError` so that the entire trace is not printed.

```
WARNING  lbry.file.file_manager:251: Failed to download Non-existing: Failed to resolve 'Could not find claim at "Non-existing".'.
WARNING  lbry.extras.daemon.daemon:1106: Error downloading Non-existing: Failed to resolve 'Could not find claim at "Non-existing".'.
```

2021-08-17 14:52 UTC, eukreign requested changes
Thanks for this PR, please add an integration test which reproduces this problem and then shows that the fix resolves the problem.

2021-08-21 23:49 UTC, belikor commented
Now all old tests pass, except for these new Coveralls tests.

2021-08-23 17:24 UTC, belikor commented
All tests pass now.

2021-09-07 14:02 UTC, eukreign commented
@belikor this needs an integration test which reproduces the problem and then shows that the PR fixes it

2021-09-12 22:20 UTC, belikor commented
Okay, it will take a while.

2021-11-15 16:14 UTC, closed without merging