wallet import export feature
lbryio/lbry-sdk pull request #3637
Opened 2022-07-22 13:40 UTC by jessopb

@eukreign Recommended a wallet import / output method rather than altering the behavior of sync apply. This does not force reset the wallet encrypt password with the import/export data encrypt password.

2022-07-25 14:50 UTC, eukreign requested changes
is this PR ready for one final review?

2022-07-25 14:50 UTC, eukreign commented on lbry/extras/daemon/daemon.py
> +            --password=<password>         : (str) password to decrypt incoming and encrypt outgoing data
probably removing the "incoming" part in the help string

2022-08-01 12:32 UTC, jessopb commented
> Review?

Yes please

2022-08-01 13:43 UTC, eukreign approved these changes

2022-08-01 14:04 UTC, merged